---
title: "Gut passage time"
author: "Elena Quintero"
date: "14/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LINEAR REGRESION PASSAGE TIMES - BODY SIZE
```{r Include data}
library(readr)
gpt<- read.csv("../../code/Gut transit time/gut_passage.csv", header=T, sep=";")
gpt
```

```{r Logarythm conversion and data distribution}
gpt$bodylog <- log(gpt$body.mass)
hist(gpt$bodylog)
gpt$passagelog <- log(gpt$seed.passage..min.)
hist(gpt$passagelog)
```
Not very normal distribution.. Is this a big problem? 

```{r model plotting}
plot(gpt$bodylog, gpt$passagelog)
model <- lm(passagelog~bodylog, gpt)
summary(model)
abline(model)
```

```{r Correlation test}
cor.test(gpt$seed.passage..min., gpt$body.mass, method="pearson", use= "pairwise.complete.obs") # with raw data
cor.test(gpt$passagelog, gpt$bodylog, method="pearson", use= "pairwise.complete.obs") #with log converted data
```
```{r Add bird studied data}
BM_studied <- read.table("../../data/birds_incl_BM.txt", header= T, sep= "\t", 
                 dec = ".", na.strings = "NA")

```

```{r data inference}
# First need to convert body mass to log to make inference
BM_studied$bodylog <- log(BM_studied$body_mass)
#Infer estimated values of gut passage time for body mass
BM_studied$passagetime<- exp(predict(model, BM_studied))
str(BM_studied)
```
```{r Save in csv}
#save results in data.csv
write.csv(BM_studied, "gpt_inferred.csv")
```

