---
title: "plant phylogeny"
author: "Elena Quintero"
date: "21/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library (ape)
#Trees obtained with Phylomatic
tree<- "((((((((((((((((((((((((((((((((((Citharexylum_myrianthum)citharexylum)verbenaceae))))))))))lamiales,((((((((((((((((((((acnistus_arborescens))iochrominae))))physaleae))))))))solanoideae))))solanaceae))solanales)))lamiids,(((((((((((Schefflera_morototoni)schefflera)araliaceae)))))apiales))))campanulids),(((((((Myrsine_umbellata,Myrsine_coriacea,Myrsine_gardneriana)myrsine)primulaceae)))))ericales)ericales_to_asterales)asterids),(((((Phoradendron_affine,Phoradendron_crassifolium,Phoradendron_piperoides)phoradendron)santalaceae)))santalales)),((((((((((Copaifera_langsdorffii)copaifera)fabaceae))fabales,(((((((Trema_micrantha)trema)cannabaceae,(((Cecropia_glaziovii,Cecropia_pachystachya)cecropia)urticaceae,(((((Ficus_benjamina)ficus))),(((Sorocea_ilicifolia)sorocea)))moraceae)))))rosales)),(((((((Erythroxylum_ambiguum)erythroxylum)erythroxylaceae)),(((Alchornea_glandulosa,Alchornea_triplinervia)alchornea)euphorbiaceae))malpighiales,((((((Sloanea_guianensis)sloanea)elaeocarpaceae))))oxalidales))celastrales_to_malpighiales))fabids,((((((((((Cupania_oblongifolia)cupania)sapindaceae,(((Cabralea_canjerana)cabralea)meliaceae)),((((Protium_heptaphyllum)protium)burseraceae,((Schinus_terebinthifolius)schinus,(Tapirira_guianensis)tapirira)anacardiaceae)))))sapindales))),((((((((((((((((((Eugenia_umbelliflora,Eugenia_uniflora)eugenia)eugeniagroup))))))myrteae)myrteaestem))))myrtaceae),(((Miconia_prasina,Miconia_pusilliflora)miconia)melastomataceae))))myrtales))malvids))rosids)))core_eudicots)trochodendrales_to_asterales)sabiales_to_asterales)eudicots)ceratophyllales_and_eudicots,((((((((((Euterpe_edulis)euterpe)arecaceae)arecales)commelinids))))))monocots)poales_to_asterales,(((((((((Nectandra_megapotamica)nectandra,(Ocotea_pulchella)ocotea)lauraceae))))laurales,(((Virola_bicuhyba,Virola_oleifera,Virola_sebifera)virola)myristicaceae,(((Magnolia_ovata)magnolia)magnoliaceae))magnoliales))magnoliids))magnoliales_to_asterales)austrobaileyales_to_asterales)nymphaeales_to_asterales)angiosperms)seedplants)euphyllophyte;"

#Strip all single-descendent nodes
mytree2 <-"(((((((Citharexylum_myrianthum,acnistus_arborescens),Schefflera_morototoni),(Myrsine_umbellata,Myrsine_coriacea,Myrsine_gardneriana)myrsine)ericales_to_asterales,(Phoradendron_affine,Phoradendron_crassifolium,Phoradendron_piperoides)phoradendron),(((Copaifera_langsdorffii,(Trema_micrantha,((Cecropia_glaziovii,Cecropia_pachystachya)cecropia,(Ficus_benjamina,Sorocea_ilicifolia)moraceae))),((Erythroxylum_ambiguum,(Alchornea_glandulosa,Alchornea_triplinervia)alchornea)malpighiales,Sloanea_guianensis)),(((Cupania_oblongifolia,Cabralea_canjerana),(Protium_heptaphyllum,(Schinus_terebinthifolius,Tapirira_guianensis)anacardiaceae)),((Eugenia_umbelliflora,Eugenia_uniflora)eugenia,(Miconia_prasina,Miconia_pusilliflora)miconia))malvids)),Euterpe_edulis)poales_to_asterales,((Nectandra_megapotamica,Ocotea_pulchella)lauraceae,((Virola_bicuhyba,Virola_oleifera,Virola_sebifera)virola,Magnolia_ovata)magnoliales))magnoliales_to_asterales;"

#Adding dummie species
mytree3<- "(((((((((Cecropia_glaziovii,Cecropia_pachystachya)cecropia,((Ficus_2,Ficus_benjamina)ficus,(Sorocea_ilicifolia,Sorocea_2)sorocea)moraceae),(Trema_2,Trema_micrantha)trema),(Copaifera_langsdorffii,Copaifera_2)copaifera),(((Alchornea_glandulosa,Alchornea_triplinervia)alchornea,(Erythroxylum_ambiguum,Erythroxylum_2)erythroxylum)malpighiales,(Sloanea_guianensis,Sloanea_2)sloanea)),((((Cupania_oblongifolia,Cupania_2)cupania,(Cabralea_canjerana,Cabralea_2)cabralea),((Protium_heptaphyllum,Protium_2)protium,((Schinus_terebinthifolius,Schinus_2)schinus,(Tapirira_guianensis,Tapirira_2)tapirira)anacardiaceae)),((Miconia_prasina,Miconia_pusilliflora)miconia,(Eugenia_umbelliflora,Eugenia_uniflora)eugenia))malvids),(((((Citharexylum_myrianthum,Citharexylum_2)citharexylum,(Acnistus_2,acnistus_arborescens)solanaceae),(Schefflera_morototoni,Schefflera_2)schefflera),(Myrsine_coriacea,Myrsine_gardneriana,Myrsine_umbellata)myrsine)ericales_to_asterales,(Phoradendron_piperoides,Phoradendron_affine,Phoradendron_crassifolium)phoradendron)),(Euterpe_edulis,Euterpe_2)euterpe)poales_to_asterales,(((Magnolia_ovata,Magnolia_2)magnolia,(Virola_bicuhyba,Virola_oleifera,Virola_sebifera)virola)magnoliales,((Nectandra_megapotamica,Nectandra_2)nectandra,(Ocotea_pulchella,Ocotea_2)ocotea)lauraceae))magnoliales_to_asterales;"
```

```{r}
write.nexus(mytree3, file="mytree.nex")
```

