---
title: "Cecropia SDE"
author: "Elena Quintero"
date: "18/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cecropia Effectiveness Landscape
```{r input}
cecropia <- read.csv("Cecropia.csv", sep = ";", header = T)
names(cecropia)

#Data without points that only specify genera (ex. Dacnis sp.)
mysp2 <- c(1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,38,39,40,41,42,43)
cecropiasp2 <- cecropia[mysp2,]

#Also without outliers Brotogeris & Pyhurra
mysp <- c(1,2,4,5,6,7,8,9,10,11,13,14,15,16,17,19,20,21,22,24,25,26,27,28,29,30,31,32,34,35,36,38,39,40,41,42,43)
cecropiasp <- cecropia[mysp,]
```

```{r SDE landscape}
library(devtools)
library(ggplot2)
library(ggrepel)
install_github("Pakillo/effectiveness_pckg", force=TRUE)
library(effect.lndscp)
effectiveness_plot(q1=cecropiasp$visit_rate, q2=cecropiasp$bic_visit, 
                   q1.error=cecropiasp$visit_rate_SE,q2.error = cecropiasp$bic_visit_SE,
                   pts.color=cecropiasp$fam, label=cecropiasp$species, nlines = 5,
                   lines.color = "light grey", pts.size=2.5,
                   myxlab= "Visitation frequency", myylab= "Bites per visit")
```
```{r SDE without error bars}
b <-effectiveness_plot(q1=cecropiasp2$visit_rate, q2=cecropiasp2$bic_visit, 
                       q1.error=NULL,q2.error = NULL,
                       pts.color=cecropiasp2$fam, label=cecropiasp2$species, 
                       nlines = 5, lines.breaks = c(0.1, 0.5, 1,3,5,8),
                       lines.color = "light grey", pts.size=3,
                       myxlab= "Visitation frequency (visits/h)", myylab= "N. of bites per visit")
b+geom_point(shape = 21, colour = "black", size=3) #Including black countour to points
#geom_point(aes(colour = factor(cecropiasp$fam)), shape = 21, size=3, fill="white", stroke = 2)
```

